name: GCC 14

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gcc:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      c_compiler: gcc-14
      cpp_compiler: g++-14
