name: MSVC 2022

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  msvc:
    uses: ./.github/workflows/build.yml
    with:
      os: windows-latest
      c_compiler: cl
      cpp_compiler: cl
